### ISSUE TITLE
URI <=> URI::Template confusion

### ISSUE THREAD

**Issue by librasteve** [jonathanstowe/URI-Template#4]
% zef info URI

for some reason, my new rakubrew install thinks that this module is plain 'URI' --- apologies if you are the wrong recipient of this issue - let me know where to repost this 

~p6steve

Welcome to Rakudo™ v2021.10.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2021.10.

- Info for: URI
- Identity: URI::Template:ver<0.0.9>:auth<github:jonathanstowe>:api<1.0>
- Recommended By: Zef::Repository::Ecosystems<cpan>
- Installed: No
Description:     URI Templates as per https://tools.ietf.org/html/rfc6570
License:         Artistic-2.0
Source-url:      http://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/URI-Template-0.0.9.tar.gz
Provides: 1 modules
Support:
#   bugtracker: https://github.com/jonathanstowe/URI-Template/issues
#   irc:        irc:// irc.freenode.net/#perl6
#   source:     https://github.com/jonathanstowe/URI-Template.git
#   email:      jns+git@gellyfish.co.uk

**Comment by jonathanstowe** [comment]
I don't know really know what to say, it looks fine for me:

```
[jonathan@menenius URI-Template]$ zef info URI
===> Updating fez mirror: http://360.zef.pm/
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated fez mirror: http://360.zef.pm/
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
- Info for: URI
- Identity: URI:ver<0.3.3>
- Recommended By: Zef::Repository::Ecosystems<p6c>
- Installed: Yes, as URI:ver<0.3.1>
Description:	 A URI implementation using Raku grammars to implement RFC 3986 BNF
License:	 Artistic-2.0
Source-url:	 git://github.com/raku-community-modules/URI.git
Provides: 9 modules
Support:
#   source:	https://github.com/raku-community-modules/URI.git
#   bugtracker:	https://github.com/raku-community-modules/URI/issues
Depends: 0 items
[jonathan@menenius URI-Template]$ zef info URI
- Info for: URI
- Identity: URI:ver<0.3.3>
- Recommended By: Zef::Repository::Ecosystems<p6c>
- Installed: Yes, as URI:ver<0.3.1>
Description:	 A URI implementation using Raku grammars to implement RFC 3986 BNF
License:	 Artistic-2.0
Source-url:	 git://github.com/raku-community-modules/URI.git
Provides: 9 modules
Support:
#   source:	https://github.com/raku-community-modules/URI.git
#   bugtracker:	https://github.com/raku-community-modules/URI/issues
Depends: 0 items
[jonathan@menenius URI-Template]$ zef info URI::Template
- Info for: URI::Template
- Identity: URI::Template:ver<0.0.9>:auth<github:jonathanstowe>:api<1.0>
- Recommended By: Zef::Repository::Ecosystems<cpan>
- Installed: Yes
Description:	 URI Templates as per https://tools.ietf.org/html/rfc6570
License:	 Artistic-2.0
Source-url:	 http://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/URI-Template-0.0.9.tar.gz
Provides: 1 modules
Support:
#   source:	https://github.com/jonathanstowe/URI-Template.git
#   email:	jns+git@gellyfish.co.uk
#   bugtracker:	https://github.com/jonathanstowe/URI-Template/issues
#   irc:	irc:// irc.freenode.net/#perl6
Depends: 2 items

```

The `META6` of `URI::Template`  has the right `name` and `provides` and as far as I know, that's the only way the module itself can affect that.  I can only imagine that it was a glitch in the indexes that zef uses or something.

**Comment by librasteve** [comment]
Hi @jonathanstowe - yes, I see that this maybe an issue with zef indexes - just thought it may be helpful if you know this data point in case anyone else has issues... next time I will post to the zef issues... thanks!
